### ISSUE TITLE
MI RECOMPENSA DE STAKING NO PUEDO OBTENERLA

### ISSUE THREAD

**Issue by hugosperu** [OVR-Platform/stakingV2#1]
MI RECOMPENSA DE STAKING NO PUEDO OBTENERLA, SE QUEDO COLGADO EN EL STAKING DE OVR, SOLICITO ME AYUDE A RECUPERARLO

**Comment by hugosperu** [comment]
MI CAPITAL SE CONVIRTIO DE CREDITOS DE REPLANTEO OVR Y NO PUEDO SACARLO, AYUDENME

**Comment by 4x22** [comment]
If you are talking about StakingV1, please try using the smart contract through Etherscan. Here a little guide.

1) Withdrawal Rewards
https://etherscan.io/address/0xdb4166b807f9a918e560a814f806288b86da3743#writeContract#F7
Go here, Connect to Web3, after you connect your wallet select tab: makeWithdrawalRewards and insert the correct value based on the lockup you used:
**1** - no Lockup
**2** - 3 months lockup
**3** - 6 months lockup
Confirm transaction and enjoy your reward.

2) Withdrawal Balances
https://etherscan.io/address/0xdb4166b807f9a918e560a814f806288b86da3743#readContract#F3
Connect wallet and read your balance, you have to insert your address and lockupTipe, as above
balances(address, lockupTipe(1|2|3))
_Copy the output_ and insert it here:
https://etherscan.io/address/0xdb4166b807f9a918e560a814f806288b86da3743#writeContract#F6
makeWithdrawal(lockupTipe(1|2|3), _copied output_)

NOTE: If transaction gas fees seem crazy expensive, it's just a glitch in the fees estimation. Click "change suggested fee" in the transaction prompt and set gasLimit to 120000. If you are having problems please seek support on Telegram.
